# Generated by Django 3.1.8 on 2021-06-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('clip_id', models.IntegerField(unique=True)),
                ('url', models.URLField()),
                ('embed_url', models.URLField()),
                ('slug', models.CharField(max_length=100)),
                ('thumbnail_url', models.URLField()),
                ('curator', models.CharField(max_length=25)),
                ('clip_url', models.URLField()),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
