# Generated by Django 3.2.8 on 2021-10-23 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strolchguru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='custom_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clip',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
    ]
