# Generated by Django 3.2.8 on 2021-11-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strolchguru', '0002_auto_20211024_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='tags',
            field=models.ManyToManyField(to='strolchguru.Tag'),
        ),
    ]
