# Generated by Django 3.2.8 on 2021-11-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strolchguru', '0004_auto_20211114_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='custom_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
