# Generated by Django 4.0.4 on 2022-05-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strolchguru', '0005_alter_clip_custom_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='is_in_loop',
            field=models.BooleanField(default=True),
        ),
    ]
