# Generated by Django 4.0.4 on 2022-05-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strolchguru', '0007_alter_clip_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='last_played',
            field=models.DateTimeField(null=True),
        ),
    ]
