# Generated by Django 3.1.2 on 2020-12-30 17:39

from django.db import migrations, models
import strolchibot.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klassenbuch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sticker', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TextCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=50)),
                ('refresh_token', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', strolchibot.managers.TwitchUserManager()),
            ],
        ),
    ]
