# Generated by Django 3.1.2 on 2021-01-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strolchibot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textcommand',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
