# Generated by Django 3.1.2 on 2021-01-20 23:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('strolchibot', '0005_auto_20210108_0031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextCommand',
            new_name='Command',
        ),
    ]
