# Generated by Django 3.2.8 on 2021-11-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strolchibot', '0007_auto_20211114_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
