# Generated by Django 3.2.8 on 2021-12-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strolchibot', '0008_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streamer', models.TextField(max_length=50, unique=True)),
                ('access_token', models.TextField(max_length=200)),
                ('token_type', models.TextField(max_length=20)),
                ('expires_in', models.IntegerField()),
                ('refresh_token', models.TextField(max_length=200)),
                ('scope', models.TextField(max_length=100)),
                ('user_id', models.TextField(max_length=50)),
            ],
        ),
    ]
