# Generated by Django 4.0.7 on 2022-08-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strolchibot', '0011_auto_20211220_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='permissions',
            field=models.CharField(choices=[('EO', 'Everyone'), ('SUB', 'Subscriber'), ('MOD', 'Moderator')], default='EO', max_length=5),
        ),
    ]
