# Generated by Django 4.1.2 on 2022-10-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strolchibot', '0012_command_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='timers_interval',
            field=models.IntegerField(default=10, verbose_name='Interval'),
        ),
    ]
